[project]
name = "audiocomprehender"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
requires-python = ">=3.13"
dependencies = [
    "pandas (>=3.0.5,<4.0.0)",
    "transformers[torch] (>=5.17.0,<6.0.0)",
    "scikit-learn (>=1.9.1,<2.0.0)",
    "torchcodec (>=0.16.0,<0.17.0)",
    "soundfile (>=0.14.0,<0.15.0)",
    "torch (>=2.14.0,<3.0.0)",
    "torchaudio (>=2.11.0,<3.0.0)",
    "faster-whisper (>=1.2.1,<2.0.0)",
    "pyannote-audio (>=4.0.7,<5.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "nvidia-cublas-cu12 (>=12.9.2.10,<13.0.0.0)",
    "nvidia-cudnn-cu12 (>=9,<10)",
    "openai (>=3.19.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
priority = "explicit"

[tool.poetry.dependencies]
torch = {source = "pytorch-cu130"}
torchaudio = {source = "pytorch-cu130"}
